name: evaluate

on:
  push:
    paths:
      - "submissions/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  evaluate:
    name: Evaluate submissions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install package
        run: python -m pip install .

      - name: Evaluate
        run: >-
          python src/run.py --evaluate --submission all
